name: "Setup NPM Job"
description: "Sets up an authorized NPM job"

inputs:
  service:
    required: true
    description: "The service to setup"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install npm modules
      shell: bash
      run: |
        cd ${{inputs.service}}
        npm ci
